# Generated by Django 5.2.17 on 2026-09-03 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0003_participant_profile_asset_and_platform_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('date_label', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('publication_status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to='seasons.event')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=180)),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=240)),
                ('original_title', models.CharField(blank=True, max_length=240)),
                ('statement_markdown', models.TextField()),
                ('source_path', models.CharField(blank=True, max_length=400)),
                ('translation_status', models.CharField(choices=[('ai_translation', 'AI-tarjima'), ('reviewed_translation', 'Tekshiruvdan o‘tgan tarjima'), ('original_uzbek', 'O‘zbekcha original')], default='ai_translation', max_length=30)),
                ('problem_type', models.CharField(choices=[('standard', 'Standart'), ('interactive', 'Interaktiv'), ('output_only', 'Faqat output'), ('communication', 'Kommunikatsion'), ('two_step', 'Ikki bosqichli')], default='standard', max_length=30)),
                ('time_limit_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty_label', models.CharField(blank=True, max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('publication_status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('last_verified_on', models.DateField(blank=True, null=True)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.problemset')),
            ],
            options={
                'ordering': ('problem_set__order', 'order', 'code', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProblemAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=1000)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='problems.problem')),
            ],
            options={
                'ordering': ('order', 'title'),
                'constraints': [models.UniqueConstraint(fields=('problem', 'url'), name='unique_problem_attachment_url')],
            },
        ),
        migrations.CreateModel(
            name='ProblemLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('original', 'Original shart'), ('practice', 'Yechish'), ('editorial', 'Tahlil'), ('package', 'Masala paketi'), ('solution', 'Yechim')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=1000)),
                ('platform', models.CharField(blank=True, max_length=80)),
                ('is_official', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='problems.problem')),
            ],
            options={
                'ordering': ('order', 'title'),
                'constraints': [models.UniqueConstraint(fields=('problem', 'kind', 'url'), name='unique_problem_link_kind_url')],
            },
        ),
        migrations.AddIndex(
            model_name='problemset',
            index=models.Index(fields=['event', 'publication_status', 'order'], name='problems_pr_event_i_f44ddd_idx'),
        ),
        migrations.AddConstraint(
            model_name='problemset',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_event_problem_set_slug'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['publication_status', 'problem_set', 'order'], name='problems_pr_publica_26227a_idx'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('problem_set', 'slug'), name='unique_problem_set_problem_slug'),
        ),
        migrations.AddConstraint(
            model_name='problem',
            constraint=models.UniqueConstraint(fields=('problem_set', 'code'), name='unique_problem_set_problem_code'),
        ),
    ]
