# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="statement_pdf_language",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="problem",
            name="statement_pdf_page_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="statement_pdf_provenance",
            field=models.CharField(
                blank=True,
                choices=[("official", "Rasmiy"), ("generated", "cp.uz tayyorlagan")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="statement_pdf_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="problem",
            name="statement_pdf_size_bytes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="statement_pdf_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
