# Generated by Django 5.2.17 on 2026-08-31 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_glossaryquizscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryquizscore',
            options={'ordering': ('-correct_answers', '-best_streak', 'total_answers', 'updated_at', 'id')},
        ),
        migrations.RemoveConstraint(
            model_name='glossaryquizscore',
            name='glossary_quiz_score_valid',
        ),
        migrations.RemoveField(
            model_name='glossaryquizscore',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='glossaryquizscore',
            name='best_correct',
        ),
        migrations.RemoveField(
            model_name='glossaryquizscore',
            name='best_total',
        ),
        migrations.AddField(
            model_name='glossaryquizscore',
            name='best_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryquizscore',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryquizscore',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glossaryquizscore',
            name='total_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='glossaryquizscore',
            constraint=models.CheckConstraint(condition=models.Q(('correct_answers__lte', models.F('total_answers'))), name='glossary_quiz_score_valid'),
        ),
        migrations.AddConstraint(
            model_name='glossaryquizscore',
            constraint=models.CheckConstraint(condition=models.Q(('current_streak__lte', models.F('best_streak'))), name='glossary_quiz_streak_valid'),
        ),
    ]
