# Generated by Django 5.2.17 on 2026-09-04 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engagement", "0004_glossaryquizanswer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="glossaryquizscore",
            index=models.Index(
                fields=["-correct_answers", "-best_streak", "total_answers", "updated_at", "id"],
                name="quiz_leaderboard_order_idx",
            ),
        ),
        migrations.CreateModel(
            name="GlossaryQuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("mode", models.CharField(max_length=40)),
                ("mode_label", models.CharField(max_length=80)),
                ("instruction", models.CharField(max_length=160)),
                ("prompt", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.CharField(max_length=400)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("selected_answer", models.CharField(blank=True, max_length=400)),
                ("is_correct", models.BooleanField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glossary_quiz_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="glossaryquizanswer",
            name="question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer_record",
                to="engagement.glossaryquizquestion",
            ),
        ),
        migrations.AddIndex(
            model_name="glossaryquizquestion",
            index=models.Index(
                fields=["user", "answered_at", "expires_at"], name="quiz_open_question_idx"
            ),
        ),
    ]
