import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=240)),
                ("slug", models.SlugField(max_length=260, unique=True)),
                ("canonical_path", models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ("content_path", models.CharField(blank=True, max_length=500)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("summary", models.TextField()),
                ("content", models.TextField(help_text="CommonMark/Markdown matni")),
                ("status", models.CharField(choices=[("draft", "Qoralama"), ("in_review", "Ko‘rib chiqilmoqda"), ("published", "Nashr qilingan"), ("archived", "Arxivlangan")], default="draft", max_length=20)),
                ("visibility", models.CharField(choices=[("private", "Yopiq"), ("unlisted", "Faqat havola orqali"), ("public", "Ochiq")], default="private", max_length=20)),
                ("difficulty", models.CharField(choices=[("beginner", "Boshlang‘ich"), ("intermediate", "O‘rta"), ("advanced", "Yuqori")], default="beginner", max_length=20)),
                ("language", models.CharField(default="uz-latn", max_length=10)),
                ("estimated_reading_minutes", models.PositiveSmallIntegerField(default=5)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("cover_image_url", models.URLField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("source_repository", models.URLField(blank=True)),
                ("source_path", models.CharField(blank=True, max_length=500)),
                ("source_commit", models.CharField(blank=True, max_length=64)),
                ("content_license", models.CharField(default="CC-BY-SA-4.0", max_length=80)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(db_index=True, editable=False, max_length=64)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=170)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="articles_created", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="articles_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("category__order", "order", "title")},
        ),
        migrations.CreateModel(
            name="ArticlePrerequisite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prerequisite_links", to="articles.article")),
                ("prerequisite", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="unlock_links", to="articles.article")),
            ],
            options={"ordering": ("order", "prerequisite__title")},
        ),
        migrations.AddField(
            model_name="article",
            name="prerequisites",
            field=models.ManyToManyField(blank=True, related_name="unlocks", through="articles.ArticlePrerequisite", through_fields=("article", "prerequisite"), to="articles.article"),
        ),
        migrations.CreateModel(
            name="ArticleRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=240)),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("change_summary", models.CharField(blank=True, max_length=500)),
                ("source_commit", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="articles.article")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="article_revisions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-version",)},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=80)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="articles.category")),
            ],
            options={"verbose_name_plural": "categories", "ordering": ("order", "name")},
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="articles", to="articles.category"),
        ),
        migrations.CreateModel(
            name="ExternalPracticeReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("platform", models.CharField(choices=[("codeforces", "Codeforces"), ("atcoder", "AtCoder"), ("cses", "CSES"), ("kattis", "Kattis"), ("spoj", "SPOJ"), ("leetcode", "LeetCode"), ("kep", "KEP.uz"), ("other", "Boshqa")], max_length=30)),
                ("custom_platform", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(max_length=240)),
                ("url", models.URLField(max_length=700)),
                ("difficulty_label", models.CharField(blank=True, max_length=80)),
                ("level", models.CharField(choices=[("warm_up", "Qizish"), ("recommended", "Tavsiya etiladi"), ("challenge", "Murakkab sinov")], default="recommended", max_length=20)),
                ("note", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="practice_references", to="articles.article")),
            ],
            options={"ordering": ("order", "title")},
        ),
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("term", models.CharField(max_length=160, unique=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("short_definition", models.CharField(max_length=400)),
                ("definition", models.TextField()),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="glossary_terms_created", to=settings.AUTH_USER_MODEL)),
                ("related_articles", models.ManyToManyField(blank=True, related_name="glossary_terms", to="articles.article")),
            ],
            options={"ordering": ("term",)},
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="articles", to="articles.tag"),
        ),
        migrations.CreateModel(
            name="ArticleContributor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(choices=[("author", "Muallif"), ("translator", "Tarjimon"), ("editor", "Muharrir"), ("technical_reviewer", "Texnik reviewer"), ("language_reviewer", "Til revieweri")], max_length=30)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("article", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contributors", to="articles.article")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="article_contributions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("order", "created_at"),
                "constraints": [models.UniqueConstraint(fields=("article", "user", "role"), name="unique_article_contributor_role")],
            },
        ),
        migrations.AddConstraint(model_name="articleprerequisite", constraint=models.UniqueConstraint(fields=("article", "prerequisite"), name="unique_article_prerequisite")),
        migrations.AddConstraint(model_name="articleprerequisite", constraint=models.CheckConstraint(condition=models.Q(("article", models.F("prerequisite")), _negated=True), name="article_prerequisite_not_self")),
        migrations.AddConstraint(model_name="articlerevision", constraint=models.UniqueConstraint(fields=("article", "version"), name="unique_article_revision")),
        migrations.AddIndex(model_name="category", index=models.Index(fields=["is_active", "order"], name="category_active_order_idx")),
        migrations.AddConstraint(model_name="externalpracticereference", constraint=models.UniqueConstraint(fields=("article", "url"), name="unique_article_practice_url")),
        migrations.AddIndex(model_name="article", index=models.Index(fields=["visibility", "language", "order"], name="article_public_lang_idx")),
        migrations.AddIndex(model_name="article", index=models.Index(fields=["category", "status", "order"], name="article_category_idx")),
        migrations.AddIndex(model_name="article", index=models.Index(fields=["status", "difficulty", "published_at"], name="article_difficulty_idx")),
    ]
