# Generated by Django 5.2 on 2026-09-03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedbackSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=160)),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(max_length=3000)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("sent", "Telegram’ga yuborildi"),
                            ("failed", "Yuborilmadi"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                ("delivery_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["delivery_status", "created_at"], name="feedback_delivery_idx"
                    )
                ],
            },
        ),
    ]
