"""Resolve a deliberate dependency update without reusing the existing constraints.

Run on the supported Python version, review the resulting constraints diff and
run CI on Linux. Constraints limit versions; they do not force marker-specific
packages to install on other platforms.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def lock(requirements, output):
    with tempfile.TemporaryDirectory(prefix="cpuz-dependency-lock-") as value:
        temporary = Path(value)
        for source in requirements.parent.glob("*.txt"):
            if source.name == "constraints.txt":
                continue
            lines = [
                line
                for line in source.read_text(encoding="utf-8").splitlines()
                if not line.lstrip().startswith(("-c ", "--constraint ", "--constraint="))
            ]
            (temporary / source.name).write_text("\n".join(lines) + "\n", encoding="utf-8")
        report = temporary / "report.json"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--dry-run",
                "--ignore-installed",
                "--report",
                str(report),
                "-r",
                str(temporary / requirements.name),
            ],
            check=True,
        )
        packages = {
            item["metadata"]["name"].lower().replace("_", "-"): item["metadata"]["version"]
            for item in json.loads(report.read_text(encoding="utf-8"))["install"]
        }
        text = (
            "# Generated by python scripts/lock_dependencies.py; review upgrades and run CI.\n"
            "# Constraints pin resolution without forcing platform-specific dependencies.\n"
            + "\n".join(f"{name}=={version}" for name, version in sorted(packages.items()))
            + "\n"
        )
        output.write_text(text, encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--requirements", type=Path, default=ROOT / "backend/requirements/dev.txt")
    parser.add_argument(
        "--output", type=Path, default=ROOT / "backend/requirements/constraints.txt"
    )
    args = parser.parse_args()
    lock(args.requirements.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
