import type { RoadmapStage } from '../entities';

export const roadmapStages: RoadmapStage[] = [
  {
    id: 'fundamentals',
    order: 1,
    eyebrow: 'Poydevor',
    title: 'Algoritmik fikrlash poydevori',
    description:
      'Qidiruv oralig‘ini toraytirish, bitlar, tez darajaga oshirish va oddiy sonli algoritmlar orqali kodning nima uchun tez ishlashini tushuning.',
    objective:
      'Maqsad: murakkablikni baholash, invariantni ko‘rish va tayyor formulani yodlamasdan asosiy algoritmni mustaqil yozish.',
    duration: '2–3 hafta',
    prerequisiteStageIds: [],
    articleSlugs: [
      'num_methods--binary_search',
      'algebra--bit-manipulation',
      'algebra--binary-exp',
      'algebra--euclid-algorithm',
      'algebra--fibonacci-numbers',
      'data_structures--stack_queue_modification',
    ],
    color: '#036FDC',
  },
  {
    id: 'number-theory',
    order: 2,
    eyebrow: 'Sonlar',
    title: 'Sonlar nazariyasi',
    description:
      'Tub sonlar va faktorizatsiyadan boshlab, kengaytirilgan Evklid algoritmi, modul bo‘yicha teskari element va taqqoslamalarga o‘ting.',
    objective:
      'Maqsad: bo‘linuvchanlikka oid masalani tub ko‘paytuvchilar yoki modul arifmetikasiga keltirib, yechim shartlarini isbotlash.',
    duration: '3–4 hafta',
    prerequisiteStageIds: ['fundamentals'],
    articleSlugs: [
      'algebra--sieve-of-eratosthenes',
      'algebra--factorization',
      'algebra--divisors',
      'algebra--extended-euclid-algorithm',
      'algebra--module-inverse',
      'algebra--linear_congruence_equation',
      'algebra--chinese-remainder-theorem',
    ],
    color: '#036FDC',
  },
  {
    id: 'data-structures',
    order: 3,
    eyebrow: 'Asboblar',
    title: 'Ma’lumotlar tuzilmalari',
    description:
      'Bloklarga ajratish va statik so‘rovlardan DSU, Fenwick hamda segment daraxtigacha bo‘lgan tuzilmalarni yangilash–so‘rov muvozanati orqali o‘rganing.',
    objective:
      'Maqsad: masaladagi amallarni aniqlab, xotira va vaqt chekloviga mos tuzilmani ongli tanlash hamda uning invariantini saqlash.',
    duration: '4–5 hafta',
    prerequisiteStageIds: ['fundamentals'],
    articleSlugs: [
      'data_structures--sqrt_decomposition',
      'data_structures--sparse-table',
      'data_structures--disjoint_set_union',
      'data_structures--fenwick',
      'data_structures--segment_tree',
      'data_structures--treap',
    ],
    color: '#036FDC',
  },
  {
    id: 'graph-foundations',
    order: 4,
    eyebrow: 'Bog‘lanishlar',
    title: 'Graflar poydevori',
    description:
      'BFS va DFS bilan grafni ko‘rishdan komponent, sikl, ikki bo‘laklilik, topologik tartib va eng qisqa yo‘llarga izchil o‘ting.',
    objective:
      'Maqsad: graf modelini to‘g‘ri qurish, ko‘rish holatini boshqarish va qirra vazniga qarab mos yo‘l algoritmini tanlash.',
    duration: '4–5 hafta',
    prerequisiteStageIds: ['fundamentals', 'data-structures'],
    articleSlugs: [
      'graph--breadth-first-search',
      'graph--depth-first-search',
      'graph--search-for-connected-components',
      'graph--finding-cycle',
      'graph--bipartite-check',
      'graph--topological-sort',
      'graph--dijkstra',
      'graph--01_bfs',
    ],
    color: '#036FDC',
  },
  {
    id: 'dynamic-programming',
    order: 5,
    eyebrow: 'Holatlar',
    title: 'Dinamik dasturlash',
    description:
      'Holat, o‘tish va bazaviy qiymatni sodda misollarda aniqlab, ryukzak va LIS’dan profil dinamikasi hamda optimallashtirishga o‘ting.',
    objective:
      'Maqsad: takrorlanuvchi qismmasalani topish, yetarli holat tuzish va o‘tishning to‘g‘riligini hamda murakkabligini asoslash.',
    duration: '4–6 hafta',
    prerequisiteStageIds: ['fundamentals', 'data-structures'],
    articleSlugs: [
      'dynamic_programming--intro-to-dp',
      'dynamic_programming--knapsack',
      'dynamic_programming--longest_increasing_subsequence',
      'dynamic_programming--zero_matrix',
      'dynamic_programming--profile-dynamics',
      'dynamic_programming--divide-and-conquer-dp',
    ],
    color: '#036FDC',
  },
  {
    id: 'strings',
    order: 6,
    eyebrow: 'Satrlar',
    title: 'Satr algoritmlari',
    description:
      'Xeshlash va Rabin–Karpdan prefiks hamda Z-funksiyaga, keyin palindromlar, ko‘p andoza qidiruvi va suffikslar massiviga o‘ting.',
    objective:
      'Maqsad: satrdagi takrorlanish va moslik tuzilishini chiziqli yoki logarifmik yordamchi ma’lumot bilan ifodalash.',
    duration: '4–5 hafta',
    prerequisiteStageIds: ['fundamentals', 'data-structures'],
    articleSlugs: [
      'string--string-hashing',
      'string--rabin-karp',
      'string--prefix-function',
      'string--z-function',
      'string--manacher',
      'string--aho_corasick',
      'string--suffix-array',
    ],
    color: '#036FDC',
  },
  {
    id: 'combinatorics',
    order: 7,
    eyebrow: 'Sanash',
    title: 'Kombinatorika',
    description:
      'Binomial koeffitsiyent va kombinatsiyalarni hosil qilishdan Catalan sonlari, qavslar, yulduzlar–ajratgichlar va kiritish–chiqarishga o‘ting.',
    objective:
      'Maqsad: sanash masalasidagi takroriy hisobni ajratish, mos formula yoki DP qurish va ortiqcha sanashni nazorat qilish.',
    duration: '3–4 hafta',
    prerequisiteStageIds: ['number-theory', 'dynamic-programming'],
    articleSlugs: [
      'combinatorics--binomial-coefficients',
      'combinatorics--generating_combinations',
      'algebra--factorial-divisors',
      'combinatorics--catalan-numbers',
      'combinatorics--bracket_sequences',
      'combinatorics--stars_and_bars',
      'combinatorics--inclusion-exclusion',
    ],
    color: '#036FDC',
  },
  {
    id: 'geometry',
    order: 8,
    eyebrow: 'Fazo',
    title: 'Hisoblash geometriyasi',
    description:
      'Nuqta va vektor amallaridan yo‘nalgan yuza, chiziq va kesma kesishishlari, ko‘pburchak yuzi hamda qavariq qobiqqa o‘ting.',
    objective:
      'Maqsad: geometrik munosabatni vektor ko‘paytma va aniq predikatlarga aylantirib, chegaraviy holatlarni xatosiz qayta ishlash.',
    duration: '4–5 hafta',
    prerequisiteStageIds: ['fundamentals'],
    articleSlugs: [
      'geometry--basic-geometry',
      'geometry--oriented-triangle-area',
      'geometry--segment-to-line',
      'geometry--lines-intersection',
      'geometry--check-segments-intersection',
      'geometry--area-of-simple-polygon',
      'geometry--convex-hull',
      'geometry--point-in-convex-polygon',
    ],
    color: '#036FDC',
  },
  {
    id: 'advanced-graphs',
    order: 9,
    eyebrow: 'Graf mahorati',
    title: 'Daraxtlar, komponentlar va oqimlar',
    description:
      'DFS vaqt belgilari va DSU bilimini ko‘priklar, kuchli komponentlar, ostov daraxtlar va LCA’da mustahkamlang; so‘ng oqim va matchingga o‘ting.',
    objective:
      'Maqsad: grafdagi global tuzilmani lokal invariantlar orqali ajratish va qisqartirish, daraxt yoki oqim modelida samarali yechim qurish.',
    duration: '6–8 hafta',
    prerequisiteStageIds: ['data-structures', 'graph-foundations'],
    articleSlugs: [
      'graph--bridge-searching',
      'graph--cutpoints',
      'graph--strongly-connected-components',
      'graph--mst_kruskal_with_dsu',
      'graph--mst_prim',
      'graph--lca_binary_lifting',
      'graph--euler_path',
      'graph--bellman_ford',
      'graph--all-pair-shortest-path-floyd-warshall',
      'graph--kuhn_maximum_bipartite_matching',
      'graph--edmonds_karp',
      'graph--dinic',
      'graph--2SAT',
    ],
    color: '#036FDC',
  },
  {
    id: 'specialization',
    order: 10,
    eyebrow: 'Ixtisoslashuv',
    title: 'Ilg‘or usullar',
    description:
      'Asosiy yo‘nalishlarni egallagach, daraxt dekompozitsiyalari, minimal narxli oqim, suffiks tuzilmalari, Li Chao daraxti va tez ko‘phad amallarini tanlab chuqurlashing.',
    objective:
      'Maqsad: murakkab masalani oldingi bosqichlardagi bir nechta g‘oyaga ajratish, isbot va amalga oshirish tafsilotlarini bir butun boshqarish.',
    duration: '6–10 hafta',
    prerequisiteStageIds: [
      'dynamic-programming',
      'strings',
      'geometry',
      'advanced-graphs',
    ],
    articleSlugs: [
      'graph--hld',
      'graph--centroid_decomposition',
      'graph--min_cost_flow',
      'graph--hungarian-algorithm',
      'string--suffix-automaton',
      'string--suffix-tree-ukkonen',
      'geometry--convex_hull_trick',
      'algebra--fft',
      'algebra--polynomial',
    ],
    color: '#036FDC',
  },
];
