# Generated by Django 5.2.17 on 2026-08-31 21:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=180)),
                ('title', models.CharField(max_length=240)),
                ('short_title', models.CharField(blank=True, max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('stage', 'Bosqich'), ('selection', 'Saralash'), ('training', 'Tayyorgarlik'), ('international', 'Xalqaro olimpiada'), ('unofficial', 'Norasmiy musobaqa')], max_length=24)),
                ('publication_status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('event_status', models.CharField(choices=[('tba', 'E’lon qilinadi'), ('scheduled', 'Rejalashtirilgan'), ('live', 'Davom etmoqda'), ('completed', 'Yakunlangan'), ('postponed', 'Qoldirilgan'), ('cancelled', 'Bekor qilingan')], default='tba', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'Tekshirilmagan'), ('pending', 'Tekshiruv kutilmoqda'), ('verified', 'Tekshirilgan'), ('disputed', 'Aniqlashtirilmoqda')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('date_precision', models.CharField(choices=[('tba', 'Sana noma’lum'), ('month', 'Oy aniqligida'), ('day', 'Kun aniqligida'), ('range', 'Sana oralig‘i')], default='tba', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_label', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(blank=True, default='Asia/Tashkent', max_length=80)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('tba', 'E’lon qilinadi'), ('onsite', 'Joyida'), ('online', 'Onlayn'), ('hybrid', 'Gibrid')], default='tba', max_length=10)),
                ('platform', models.CharField(blank=True, max_length=180)),
                ('organizer', models.CharField(blank=True, max_length=240)),
                ('eligibility', models.TextField(blank=True)),
                ('grade_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('grade_max', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'start_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('country_code', models.CharField(blank=True, default='UZB', max_length=3)),
                ('region', models.CharField(blank=True, max_length=160)),
                ('school', models.CharField(blank=True, max_length=240)),
                ('handle', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['country_code', 'full_name'], name='person_country_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(editable=False, max_length=200, unique=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='seasons.participant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('publication_status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr qilingan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('verification_status', models.CharField(choices=[('unverified', 'Tekshirilmagan'), ('pending', 'Tekshiruv kutilmoqda'), ('verified', 'Tekshirilgan'), ('disputed', 'Aniqlashtirilmoqda')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('-is_featured', '-order', '-start_date'),
                'indexes': [models.Index(fields=['publication_status', 'is_featured', 'order'], name='season_public_feature_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('official', 'Rasmiy olimpiada'), ('selection', 'Saralash'), ('international', 'Xalqaro olimpiada'), ('unofficial', 'Norasmiy musobaqa'), ('training', 'Rasmiy tayyorgarlik')], max_length=20)),
                ('color', models.CharField(choices=[('blue', 'Ko‘k'), ('red', 'Qizil'), ('brown', 'Jigarrang'), ('teal', 'Teal'), ('gold', 'Oltin'), ('purple', 'Binafsha'), ('green', 'Yashil'), ('neutral', 'Neytral')], default='neutral', max_length=20)),
                ('line_style', models.CharField(choices=[('solid', 'Uzluksiz'), ('dashed', 'Uzlukli'), ('dotted', 'Nuqtali')], default='solid', max_length=10)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='seasons.season')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='EventEdge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('qualifies_to', 'Keyingi bosqichga saralaydi'), ('feeds_into', 'Nomzodlar bazasiga olib boradi'), ('training_for', 'Tayyorgarlik hisoblanadi'), ('related_to', 'Aloqador')], max_length=20)),
                ('line_style', models.CharField(choices=[('solid', 'Uzluksiz'), ('dashed', 'Uzlukli'), ('dotted', 'Nuqtali')], default='solid', max_length=10)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('from_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='seasons.event')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='seasons.event')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edges', to='seasons.route')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='seasons.season')),
            ],
            options={
                'ordering': ('order', 'from_event__order', 'to_event__order'),
            },
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='seasons.season'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('country_code', models.CharField(blank=True, default='UZB', max_length=3)),
                ('school', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='seasons.event')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ResultEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(blank=True, max_length=180)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('score_label', models.CharField(blank=True, max_length=100)),
                ('medal', models.CharField(choices=[('none', 'Medalsiz'), ('gold', 'Oltin'), ('silver', 'Kumush'), ('bronze', 'Bronza'), ('honourable_mention', 'Faxriy yorliq'), ('other', 'Boshqa sovrin')], default='none', max_length=30)),
                ('award_title', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(blank=True, max_length=160)),
                ('is_local', models.BooleanField(default=True)),
                ('result_url', models.URLField(blank=True, max_length=700)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='seasons.event')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='seasons.participant')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='seasons.team')),
            ],
            options={
                'ordering': ('order', 'rank', 'participant__full_name', 'team__name'),
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('contestant', 'Ishtirokchi'), ('leader', 'Jamoa rahbari'), ('deputy', 'Rahbar o‘rinbosari'), ('coach', 'Murabbiy'), ('other', 'Boshqa')], default='contestant', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to='seasons.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='seasons.team')),
            ],
            options={
                'ordering': ('order', 'participant__full_name'),
            },
        ),
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('official_page', 'Rasmiy sahifa'), ('announcement', 'E’lon'), ('schedule', 'Jadval'), ('rules', 'Nizom va qoidalar'), ('registration', 'Ro‘yxatdan o‘tish'), ('platform', 'Platforma'), ('participants', 'Ishtirokchilar'), ('tasks', 'Masalalar'), ('editorial', 'Tahlillar'), ('scoreboard', 'Natijalar jadvali'), ('results', 'Natijalar'), ('photos', 'Rasmlar'), ('videos', 'Videolar'), ('mirror', 'Mirror'), ('other', 'Boshqa')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=700)),
                ('is_official', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='seasons.event')),
            ],
            options={
                'ordering': ('order', 'title'),
                'constraints': [models.UniqueConstraint(fields=('event', 'url'), name='unique_event_resource_url')],
            },
        ),
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('official', 'Rasmiy manba'), ('government', 'Davlat manbasi'), ('organizer', 'Tashkilotchi'), ('press', 'Matbuot'), ('archive', 'Arxiv'), ('official_page', 'Rasmiy sahifa'), ('official_announcement', 'Rasmiy e’lon'), ('official_results', 'Rasmiy natijalar'), ('official_regulation', 'Rasmiy nizom'), ('organizer_archive', 'Tashkilotchi arxivi'), ('government_news', 'Davlat yangiliklari'), ('community_report', 'Hamjamiyat xabari'), ('other', 'Boshqa')], max_length=24)),
                ('title', models.CharField(max_length=240)),
                ('url', models.URLField(max_length=700)),
                ('publisher', models.CharField(blank=True, max_length=180)),
                ('accessed_on', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='seasons.event')),
            ],
            options={
                'ordering': ('-is_primary', 'title'),
                'constraints': [models.UniqueConstraint(fields=('event', 'url'), name='unique_event_source_url')],
            },
        ),
        migrations.CreateModel(
            name='EventRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('node_style', models.CharField(choices=[('default', 'Oddiy tugun'), ('final', 'Final tuguni'), ('training', 'Tayyorgarlik tuguni')], default='default', max_length=10)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_memberships', to='seasons.event')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_memberships', to='seasons.route')),
            ],
            options={
                'ordering': ('route__order', 'order', 'event__order'),
                'constraints': [models.UniqueConstraint(fields=('event', 'route'), name='unique_event_route')],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['season', 'order'], name='route_season_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('season', 'code'), name='unique_season_route_code'),
        ),
        migrations.AddConstraint(
            model_name='eventedge',
            constraint=models.CheckConstraint(condition=models.Q(('from_event', models.F('to_event')), _negated=True), name='event_edge_not_self'),
        ),
        migrations.AddConstraint(
            model_name='eventedge',
            constraint=models.UniqueConstraint(condition=models.Q(('route__isnull', False)), fields=('from_event', 'to_event', 'relation_type', 'route'), name='unique_routed_event_edge'),
        ),
        migrations.AddConstraint(
            model_name='eventedge',
            constraint=models.UniqueConstraint(condition=models.Q(('route__isnull', True)), fields=('from_event', 'to_event', 'relation_type'), name='unique_unrouted_event_edge'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['season', 'publication_status', 'order'], name='event_season_public_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_status', 'start_date'], name='event_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('season', 'code'), name='unique_season_event_code'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('season', 'slug'), name='unique_season_event_slug'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_event_team_name'),
        ),
        migrations.AddIndex(
            model_name='resultentry',
            index=models.Index(fields=['event', 'is_local', 'rank'], name='result_event_local_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participant__isnull', False), ('team__isnull', True)), models.Q(('participant__isnull', True), ('team__isnull', False)), _connector='OR'), name='result_exactly_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='resultentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('event', 'source_key'), name='unique_event_result_source_key'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'participant', 'role'), name='unique_team_member_role'),
        ),
    ]
