# Generated by Django 5.2.17 on 2026-09-01 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='photo_url',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.CreateModel(
            name='ParticipantPlatformAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('leetcode', 'LeetCode'), ('kepuz', 'KEP.uz'), ('robocontest', 'Robocontest'), ('atcoder', 'AtCoder'), ('codechef', 'CodeChef'), ('eolymp', 'Eolymp'), ('other', 'Boshqa platforma')], max_length=24)),
                ('handle', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=700)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='seasons.participant')),
            ],
            options={
                'ordering': ('order', 'platform', 'handle'),
                'constraints': [models.UniqueConstraint(fields=('participant', 'platform', 'handle'), name='unique_participant_platform_handle')],
            },
        ),
    ]
