# Generated by Django 5.2.17 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seasons", "0002_participant_bio_participant_photo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="photo_url",
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name="participantplatformaccount",
            name="platform",
            field=models.CharField(
                choices=[
                    ("codeforces", "Codeforces"),
                    ("atcoder", "AtCoder"),
                    ("kepuz", "KEP.uz"),
                    ("robocontest", "Robocontest"),
                ],
                max_length=24,
            ),
        ),
    ]
